networks:
  default:
    external: true
    name: jps-net

services:
  crm:
    image: g19/crm
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  postgres:
    image: postgres:latest
    ports:
      - "5555:5432"
    env_file:
      - ../.env
