networks:
  default:
    external: true
    name: jps-net

services:
  crm:
    image: g19/crm
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - default # Assicurati che sia sulla rete corretta
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    ports:
      - "29092:29092" # Porta per la comunicazione ESTERNA a Docker
      - "9092:9092" # Porta per la comunicazione INTERNA a Docker
    depends_on:
      - zookeeper
    networks:
      - default
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  connect:
    # Usiamo l'immagine ufficiale di Debezium che CONTIENE Kafka Connect
    image: debezium/connect:2.5
    hostname: connect
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - postgres
    networks:
      - default
    environment:
      BOOTSTRAP_SERVERS: 'kafka:9092'
      GROUP_ID: 'connect-cluster-crm'
      CONFIG_STORAGE_TOPIC: 'connect_configs'
      OFFSET_STORAGE_TOPIC: 'connect_offsets'
      STATUS_STORAGE_TOPIC: 'connect_status'
      CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

  postgres:
    image: postgres:latest
    ports:
      - "5555:5432"
    env_file:
        - ../.env
    volumes:
        - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
