services:
  communication_manager:
    image: g19/communication_manager
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - crm2

  postgres:
    image: postgres:latest
    ports:
      - "5556:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: